### ISSUE TITLE
missing license for the repo

### ISSUE THREAD

**Issue by chenrui333** [ap/rename#12]
👋 Just found this repo does not have any license, it would be good to add OSI-approved one, https://spdx.org/licenses/

Some popular license choice would be:
- MIT
- Apache-2.0
- BSD-3-Clause

**Comment by ap** [comment]
The documentation inside the program [already said](/ap/rename/blob/644826c376384e9724c5de5975efde843be221fc/rename#L637) it is under the same terms as Perl (essentially dual Artistic/GPL), which is the usual way to license libre Perl stuff.

But I’ve pushed 0da9faa241093c90a40b15a9ff4b36e9858d4516 to also make it easy for people who don’t deal much with Perl stuff.

**Comment by chenrui333** [comment]
Thanks @ap!
