### ISSUE TITLE
Can you add a release or tag?

### ISSUE THREAD

**Issue by magnusviri** [ap/rename#17]
Hi, I was hoping you could create a release for this really awesome tool. https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Comment by ap** [comment]
[There already are](/ap/rename/tags). Do you mean you would like a release of the current `master`?

**Comment by magnusviri** [comment]
Duh! I didn't see that! Thanks for the quick reply!
